### PR TITLE
renaming dirs from 'java' to 'kotlin'

### PR DESCRIPTION
**Pull request by pwittchen**
In this PR, I'm renaming dirs:
- from: `app/src/main/java` to `app/src/main/kotlin`
- from: `app/src/test/java` to `app/src/test/kotlin`

### CODE REVIEW

**Comment by owahltinez** [comment]
Thanks for the PR @pwittchen but I'm not sure that this would work without also making some changes to the Gradle files -- specially for older versions of Android Studio. Since this is the default project structure in Android Studio, even for new Kotlin applications, we will probably stick to the current paths.

**Comment by piotrek1543** [comment]
@owahltinez I think the question is for what reason someone would use older version of Android Studio, but yes you're right I remember I had an issue with compiling project in AS 3.2 when trying to do same as in this merge request.

**Comment by pwittchen** [comment]
@owahltinez you're right. I've updated gradle configuration within my PR. I also bumped version of `androidx.core:core-ktx`. I also rebuild project in Android Studio, to verify that it works and checked if directories are marked properly and they're now.
Zrzut ekranu z 2019-05-18 10-52-42
Zrzut ekranu z 2019-05-18 11-00-42

**Comment by owahltinez** [comment]
@pwittchen what is the reason behind renaming directories? As far as I understand it, it's not the convention. Android Studio uses `java` as the default directory name and all other Android samples I'm aware of, whether they are written in Kotlin or not, use the default directory name.

I think that renaming the directories may be confusing to other developers in addition to adding complexity to Gradle files for the sake of stylistic choices. Your PR also breaks the current tests setup that allows for sharing tests between roboelectric and adb devices.

**Comment by pwittchen** [comment]
Ok, I thought that's the standard and proper convention of naming directories in projects written in Kotlin. E.g. JetBrains sample here: https://github.com/JetBrains/kotlin-examples/tree/master/gradle/hello-world has such naming convention. If that's not the standard or correct way of naming, we can close this PR.

**Pull request closed without merging**
